### ISSUE TITLE
The new `AwsCLI` task is broken and is missing a logo

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#201]
### Expected Behavior

Simple reproducer:

```yml
id: awsCli
namespace: dev

tasks:
  - id: aws
    type: io.kestra.plugin.aws.cli.AwsCLI
    accessKeyId: "{{secret('AWS_ACCESS_KEY_ID')}}"
    secretKeyId: "{{secret('AWS_SECRET_ACCESS_KEY')}}"
    region: "eu-central-1"
    commands:
      - aws s3 help
```

![image](https://github.com/kestra-io/plugin-aws/assets/86264395/bcd9da2e-b377-47be-a78b-9f734ddeb130)

### Actual Behaviour

traceback:

```
Command failed with code 252
io.kestra.plugin.scripts.exec.scripts.runners.ScriptException: Command failed with code 252
	at io.kestra.plugin.scripts.exec.scripts.runners.DockerScriptRunner.run(DockerScriptRunner.java:153)
	at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:123)
	at io.kestra.plugin.aws.cli.AwsCLI.run(AwsCLI.java:109)
	at io.kestra.plugin.aws.cli.AwsCLI.run(AwsCLI.java:27)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:641)
```

### Environment Information

- Kestra Version: 0.10.1 develop full docker

**Comment by anna-geller** [comment]
more detailed log when running standalone server:

```
2023-07-14 16:38:59,672 INFO  default-nioEventLoopGroup-1-8 io.kestra.webserver.access [Date: 2023-07-14T16:38:59.651968+02:00] [Duration: 20 ms] [Method: GET] [Url: /api/v1/flows/dev/awsCli?source=true&id=awsCli&namespace=dev&deleted=true] [Status: 200] [Length: 559] [Ip: 0:0:0:0:0:0:0:1] [Port: 8080]
2023-07-14 16:39:00,178 INFO  jdbc-queue_4 flow.awsCli  [namespace: dev] [flow: awsCli] [execution: 6Jo19yRMfyHa492cuitGMX] Flow started
2023-07-14 16:39:01,141 INFO  worker_1     flow.awsCli.aws [namespace: dev] [flow: awsCli] [task: aws] [execution: 6Jo19yRMfyHa492cuitGMX] [taskrun: xld2IOSJ9UIM8rYA8AEC] [value: null] Type AwsCLI started
2023-07-14 16:39:03,333 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC 
2023-07-14 16:39:03,337 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
2023-07-14 16:39:03,340 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC To see help text, you can run:
2023-07-14 16:39:03,344 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC 
2023-07-14 16:39:03,347 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC aws help
2023-07-14 16:39:03,350 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC aws <command> help
2023-07-14 16:39:03,353 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC aws <command> <subcommand> help
2023-07-14 16:39:03,357 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC 
2023-07-14 16:39:03,360 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC aws: error: argument command: Invalid choice, valid choices are:
2023-07-14 16:39:03,363 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC 
2023-07-14 16:39:03,365 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC accessanalyzer                           | account
2023-07-14 16:39:03,370 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC acm                                      | acm-pca
2023-07-14 16:39:03,376 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC alexaforbusiness                         | amp
2023-07-14 16:39:03,391 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC amplify                                  | amplifybackend
2023-07-14 16:39:03,398 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC amplifyuibuilder                         | apigateway
2023-07-14 16:39:03,405 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC apigatewaymanagementapi                  | apigatewayv2

...

2023-07-14 16:39:03,923 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC cli-dev                                  | help
2023-07-14 16:39:03,925 WARN  docker-java-stream--1739515382 f.a.6.xld2IOSJ9UIM8rYA8AEC 
2023-07-14 16:39:04,047 ERROR WorkerThread f.a.6.xld2IOSJ9UIM8rYA8AEC Command failed with code 252
io.kestra.plugin.scripts.exec.scripts.runners.ScriptException: Command failed with code 252
        at io.kestra.plugin.scripts.exec.scripts.runners.DockerScriptRunner.run(DockerScriptRunner.java:153)
        at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:123)
        at io.kestra.plugin.aws.cli.AwsCLI.run(AwsCLI.java:109)
        at io.kestra.plugin.aws.cli.AwsCLI.run(AwsCLI.java:27)
        at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:641)
2023-07-14 16:39:04,056 INFO  worker_1     flow.awsCli.aws [namespace: dev] [flow: awsCli] [task: aws] [execution: 6Jo19yRMfyHa492cuitGMX] [taskrun: xld2IOSJ9UIM8rYA8AEC] [value: null] Type AwsCLI with state FAILED completed in 00:00:03.877
2023-07-14 16:39:04,113 INFO  jdbc-queue_4 flow.awsCli  [namespace: dev] [flow: awsCli] [execution: 6Jo19yRMfyHa492cuitGMX] Flow completed with state FAILED in 00:00:04.581
2023-07-14 16:39:04,139 INFO  default-nioEventLoopGroup-1-4 io.kestra.webserver.access [Date: 2023-07-14T16:38:59.664611+02:00] [Duration: 4475 ms] [Method: GET] [Url: /api/v1/executions/6Jo19yRMfyHa492cuitGMX/follow] [Status: 200] [Length: 645] [Ip: 0:0:0:0:0:0:0:1] [Port: 8080]
2023-07-14 16:39:04,836 INFO  default-nioEventLoopGroup-1-4 io.kestra.webserver.access [Date: 2023-07-14T16:39:04.819623+02:00] [Duration: 16 ms] [Method: GET] [Url: /api/v1/logs/6Jo19yRMfyHa492cuitGMX?minLevel=TRACE&sort=timestamp:asc&page=1&size=100&append=false&taskRunId=xld2IOSJ9UIM8rYA8AEC] [Status: 200] [Length: 4191] [Ip: 0:0:0:0:0:0:0:1] [Port: 8080]
```

**Comment by brian-mulier-p** [comment]
Ups forgot the icon, nice spot, regarding your problem that's strange cause I had the same but after overriding the entrypoint of the docker image it was working (and I added the override to the actual task).
I'll try on monday and fix it, sorry for the inconvenience :/

**Comment by anna-geller** [comment]
no worries I should have QAed it yesterday too 😜

**Comment by brian-mulier-p** [comment]
A workaround while I find what's wrong:
add `docker: 
      image: amazon/aws-cli
      entryPoint:
        - ''
      pullPolicy: ALWAYS`
