### ISSUE TITLE
`S3Exception: null` when using the `s3.Downloads` task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#216]
### Expected Behavior

reproducer:

```yaml
id: downloadObjects
namespace: dev

variables:
  bucket: kestraio

tasks:
  - id: download
    type: io.kestra.plugin.aws.s3.Downloads
    bucket: "{{vars.bucket}}"
    prefix: inbox/
    filter: FILES
    action: MOVE
    moveTo: 
      bucket: "{{vars.bucket}}"
      key: archive/

  - id: printObjects
    type: io.kestra.core.tasks.log.Log
    message: "found objects {{outputs.download.objects}}"

taskDefaults:
  - type: io.kestra.plugin.aws.s3.Downloads
    values:
      accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
      secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
      region: "{{ secret('AWS_DEFAULT_REGION') }}"
```

### Actual Behaviour

error message:

```bash
Found '3' keys on kestraio with regexp='null', prefix=inbox/
software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: 7M5CBX6N4PHA05PS, Extended Request ID: 2KQkAT2rX5aX4za54NbzkIbhGQaPHJjmIBzNrKeR9Zc8zeoJGuM+4JlUf2Y4sg6e2JmrEUFB2yA=)
null (Service: S3, Status Code: 400, Request ID: 7M5CBX6N4PHA05PS, Extended Request ID: 2KQkAT2rX5aX4za54NbzkIbhGQaPHJjmIBzNrKeR9Zc8zeoJGuM+4JlUf2Y4sg6e2JmrEUFB2yA=)
java.util.concurrent.ExecutionException: software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: 7M5CBX6N4PHA05PS, Extended Request ID: 2KQkAT2rX5aX4za54NbzkIbhGQaPHJjmIBzNrKeR9Zc8zeoJGuM+4JlUf2Y4sg6e2JmrEUFB2yA=)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at io.kestra.plugin.aws.s3.S3Service.download(S3Service.java:43)
	at io.kestra.plugin.aws.s3.Downloads.lambda$run$0(Downloads.java:96)
	at io.kestra.core.utils.Rethrow.lambda$throwFunction$4(Rethrow.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.kestra.plugin.aws.s3.Downloads.run(Downloads.java:100)
	at io.kestra.plugin.aws.s3.Downloads.run(Downloads.java:21)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:645)
Caused by: software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: 7M5CBX6N4PHA05PS, Extended Request ID: 2KQkAT2rX5aX4za54NbzkIbhGQaPHJjmIBzNrKeR9Zc8zeoJGuM+4JlUf2Y4sg6e2JmrEUFB2yA=)
```

the documentation on this task could be improved too e.g. "Downloads files to a S3 bucket." should be "Downloads multiple files from an S3 bucket."

### Environment Information

- Kestra Version: 0.11.0

**Comment by allemas** [comment]
S3Exception is in software.amazon.awssdk, and you cant edit the mapping errors. 
I had this issue when I used the ceph object storage who respond something like this : 

```
<xml version="1.0" encoding="UTF-8"?><Error><Code>EntityTooLarge</Code><BucketName>bucket</BucketName><RequestId>tx00000000000000000</RequestId><HostId>default</HostId></Error>
```

So I suppose that `software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse()`
doesn't parse xml and can't set the Exception reason, and you have an empty string : null.
