### ISSUE TITLE
Refactor the Upload task to allow uploading multiple files

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#297]
### Feature description

https://kestra.io/plugins/plugin-aws/tasks/s3/io.kestra.plugin.aws.s3.upload

**Comment by KhalefAhmed** [comment]
Hi @anna-geller, @Ben8t,

You can upload multiple files via the s3.upload task as shown in the example below:

```yml

id: upload_multiple_files_to_s3
namespace: company.team

tasks:

  - id: download_file1
    type: io.kestra.plugin.core.http.Download
    uri: "https://wri-dataportal-prod.s3.amazonaws.com/manual/global_power_plant_database_v_1_3.zip"

  - id: download_file2
    type: io.kestra.plugin.core.http.Download
    uri: "https://wri-dataportal-prod.s3.amazonaws.com/manual/global_power_plant_database_v_1_3.zip" 

  - id: upload_multiple_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    from:
      - "{{ outputs.download_file1.uri }}"
      - "{{ outputs.download_file2.uri }}"
    key: "data/files" # Will be treated as a destination directory
    bucket: "my-bucket"
    region: "eu-west-3"
    accessKeyId: "test"
    secretKeyId: "test"
    endpointOverride: "http://127.0.0.1:4566"

````
In the object `from` the types that can be sent, [it's mentioned that](https://kestra.io/plugins/plugin-aws/s3/io.kestra.plugin.aws.s3.upload#properties_from-body:~:text=Can%20be%20a%20single%20file%2C%20a%20list%20of%20files%20or%20json%20array.) it can be a single file, a list of files, or a JSON array.

There's no error in sending a list or a file, but there is an error if you want to send a JSON array.
```text
TRACE 2025-04-25T16:02:11.471791Z java.net.URISyntaxException: Illegal character in scheme name at index 0: ["kestra:///company/team/upload-multiple-files-to-s3-4/executions/4dxsU1SGk1LlLQ4XgQjBzo/tasks/download-file1/69CmpkWVjPu623AJZNHiuH/5157374216595424600.zip","kestra:///company/team/upload-multiple-files-to-s3-4/executions/4dxsU1SGk1LlLQ4XgQjBzo/tasks/download-file2/4NKuTQNTo6RUxPpm6nDooO/3776156720132654314.zip"]
	at java.base/java.net.URI$Parser.fail(URI.java:2995)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3166)
	at java.base/java.net.URI$Parser.checkChar(URI.java:3176)
	at java.base/java.net.URI$Parser.parse(URI.java:3191)
	at java.base/java.net.URI.<init>(URI.java:645)
	at io.kestra.plugin.aws.s3.Upload.run(Upload.java:348)
	at io.kestra.plugin.aws.s3.Upload.run(Upload.java:33)
	at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78)
	at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:62)
	at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
	at io.kestra.core.runners.Worker.lambda$callJob$19(Worker.java:846)
	at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
	at io.kestra.core.runners.Worker.callJob(Worker.java:842)
	at io.kestra.core.runners.Worker.runAttempt(Worker.java:801)
	at io.kestra.core.runners.Worker.run(Worker.java:650)
	at io.kestra.core.runners.Worker.handleTask(Worker.java:344)
	at io.kestra.core.runners.Worker.lambda$run$8(Worker.java:267)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
with this example 

```yml
id: upload_multiple_files_to_s3_4
namespace: company.team

tasks:
  # Première tâche: télécharger plusieurs fichiers
  - id: download_file1
    type: io.kestra.plugin.core.http.Download
    uri: "https://wri-dataportal-prod.s3.amazonaws.com/manual/global_power_plant_database_v_1_3.zip"

  - id: download_file2
    type: io.kestra.plugin.core.http.Download
    uri: "https://wri-dataportal-prod.s3.amazonaws.com/manual/global_power_plant_database_v_1_3.zip" 

  # Tâche d'upload multiple vers S3
  - id: upload_multiple_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    from: "[\"{{ outputs.download_file1.uri }}\",\"{{ outputs.download_file2.uri }}\"]"
    key: "data/files" 
    bucket: "my-bucket"
    region: "eu-west-3"
    accessKeyId: "test"
    secretKeyId: "test"
    endpointOverride: "http://127.0.0.1:4566"
```

because in the code of the `Upload.run` method there are conditions on the content of the `from`, and if it's an instance of a String it will be treated as if it were a single object to upload, and as the json array we're sending is a string it will never be parsed into several strings, hence the error.

- the two things to do is add an example to show that you can upload several files and fix the problem on the json array

You can assign me the ticket if you want.

**Comment by MilosPaunovic** [comment]
There is a merged PR related to this issue. Does that mean it's completed and could be closed @Malaydewangan09?
