### ISSUE TITLE
AWS SQS Publish flow example fails with an error

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-aws#359]
### Expected Behavior

The flow example mentioned on this [page](https://kestra.io/plugins/plugin-aws/tasks/sqs/io.kestra.plugin.aws.sqs.Publish) should run successfully and publish a message in the SQS queue.

### Actual Behaviour

The Publish flow example on this [page](https://kestra.io/plugins/plugin-aws/tasks/sqs/io.kestra.plugin.aws.sqs.Publish) failed with the following error:

```sh
java.lang.ClassCastException: Cannot cast java.util.LinkedHashMap to io.kestra.plugin.aws.sqs.model.Message
	at java.base/java.lang.Class.cast(Unknown Source)
	at io.reactivex.internal.functions.Functions$CastToClass.apply(Functions.java:222)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.internal.operators.flowable.FlowableFromArray$ArraySubscription.fastPath(FlowableFromArray.java:132)
	at io.reactivex.internal.operators.flowable.FlowableFromArray$BaseArraySubscription.request(FlowableFromArray.java:88)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.operators.flowable.FlowableReduceMaybe$ReduceSubscriber.onSubscribe(FlowableReduceMaybe.java:94)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.operators.flowable.FlowableFromArray.subscribeActual(FlowableFromArray.java:38)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableReduceMaybe.subscribeActual(FlowableReduceMaybe.java:57)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.kestra.plugin.aws.sqs.Publish.run(Publish.java:86)
	at io.kestra.plugin.aws.sqs.Publish.run(Publish.java:26)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:684)
```

### Steps To Reproduce

With an appropriate access key, secret key and SQS queue, try out the flow example as mentioned on this [page](https://kestra.io/plugins/plugin-aws/tasks/sqs/io.kestra.plugin.aws.sqs.Publish).

### Environment Information

- Kestra Version: 0.13.8
- Plugin version: 0.13.8
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```yaml
id: "publish"
type: "io.kestra.plugin.aws.sqs.Publish"
accessKeyId: "<access-key>"
secretKeyId: "<secret-key>"
region: "eu-central-1"
queueUrl: "https://sqs.eu-central-1.amazonaws.com/000000000000/test-queue"
from:
- data: Hello World
- data: Hello Kestra
  delaySeconds: 5
```

**Comment by smunteankestra** [comment]
reproducing, needs fix

**Comment by loicmathieu** [comment]
Fixed by https://github.com/kestra-io/plugin-aws/pull/524
