### ISSUE TITLE
AWS SNS Publish task fails with an error

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-aws#363]
### Expected Behavior

The example mentioned on this [page](https://kestra.io/plugins/plugin-aws/tasks/sns/io.kestra.plugin.aws.sns.Publish) should run successfully and publish a message to a SNS topic.

### Actual Behaviour

The example mentioned on this [page](https://kestra.io/plugins/plugin-aws/tasks/sns/io.kestra.plugin.aws.sns.Publish) fails with the following error:

```sh
2024-01-28 20:09:28.954Cannot cast java.util.LinkedHashMap to io.kestra.plugin.aws.sns.model.Message
2024-01-28 20:09:28.954java.lang.ClassCastException: Cannot cast java.util.LinkedHashMap to io.kestra.plugin.aws.sns.model.Message
	at java.base/java.lang.Class.cast(Unknown Source)
	at io.reactivex.internal.functions.Functions$CastToClass.apply(Functions.java:222)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.internal.operators.flowable.FlowableFromArray$ArraySubscription.fastPath(FlowableFromArray.java:132)
	at io.reactivex.internal.operators.flowable.FlowableFromArray$BaseArraySubscription.request(FlowableFromArray.java:88)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.operators.flowable.FlowableReduceMaybe$ReduceSubscriber.onSubscribe(FlowableReduceMaybe.java:94)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.operators.flowable.FlowableFromArray.subscribeActual(FlowableFromArray.java:38)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableReduceMaybe.subscribeActual(FlowableReduceMaybe.java:57)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.kestra.plugin.aws.sns.Publish.run(Publish.java:85)
	at io.kestra.plugin.aws.sns.Publish.run(Publish.java:26)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:684)
```

### Steps To Reproduce

1. Create a flow with the task mentioned in the example on the SNS Publish task [page](https://kestra.io/plugins/plugin-aws/tasks/sns/io.kestra.plugin.aws.sns.Publish)
2. Provide correct accessKeyId, secretKeyId, region and topicArn.
3. Run the flow.

### Environment Information

- Kestra Version: 0.13.8
- Plugin version: 0.13.8
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```yaml
id: "publish"
type: "io.kestra.plugin.aws.sns.Publish"
accessKeyId: "<access-key>"
secretKeyId: "<secret-key>"
region: "eu-central-1"
topicArn: "arn:aws:sns:eu-central-1:000000000000:MessageTopic"
from:
- data: Hello World
- data: Hello Kestra
  subject: Kestra
```

Also tried by enclosing the data and subject in double quotes. Still the same error.

**Comment by joshuarestivo** [comment]
Is this a matter of the published example being wrong or does the AWS plugin have issues? II see another identical issue opened for SQS, for example.

**Comment by anna-geller** [comment]
closing, the same issue as was fixed in https://github.com/kestra-io/plugin-aws/pull/524/files
